import categoryModel from './category.js';
import lessonModel from './lesson.js';
import userModel from './user.js';
import ratingModel from './rating.js';
import eventModel from './event.js';
export const User = userModel;
export const Category = categoryModel;
export const Lesson = lessonModel;
export const Rating = ratingModel;
export const Event = eventModel;
