FROM node:18.11-alpine3.15
RUN  npm install pm2 -g
COPY . /app
WORKDIR /app
RUN npm i
EXPOSE 3000 
ENV PORT=3000
ENV NODE_ENV=production
COPY .env.prod .env
CMD [ "pm2-runtime", "npm", "--", "start" ]