FROM node:16.15
RUN  npm install pm2 -g
WORKDIR /app
COPY . .
RUN npm install --production
EXPOSE 3000 
ENV PORT=3000
ENV NODE_ENV=production
COPY .env.prod .env
CMD [ "pm2-runtime", "npm", "--", "start" ]