FROM node:18.11-alpine3.15
WORKDIR /app
RUN  npm install pm2 -g
COPY ./package.json .
RUN npm i
EXPOSE 3000 
ENV PORT=3000
ENV NODE_ENV=production
COPY . .
ENV LEARNIFY_DOCKER_DB_URI="mongodb://mongo:27017"
ENV LEARNIFY_DOCKER_ANNOTATIONS_SERVER="http://0.0.0.0:5000"
ENV LEARNIFY_DOCKER_SEMANTIC_SERVER="http://semantic:8000"
CMD [ "pm2-runtime", "npm", "--", "start" ]