export {default as get_courses} from './get_courses.js'
export {default as post_learningSpace} from './post_learning_space.js'
export {default as semanti_search_ls} from './semantic_search_learning_space.js'
export {default as get_learning_space_by_id} from './get_learning_space_by_id.js'
export {default as get_learning_space_by_category} from './get_learning_space_by_category.js'
export {default as post_create_annotation} from './post_create_annotation.js'
export {default as post_chapters} from './post_chapters.js'
