version: '3.9'
volumes:
  data:
services:
  mongodb:
    image: mongo:latest
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    networks:
      - mongo_net
  semantic-server:
    hostname: semantic
    build: 
      context: ./semantic_service
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    networks:
      - mongo_net
    depends_on:
      - mongodb
  server:
    hostname: backend
    build: 
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    networks:
      - mongo_net
    depends_on:
      - mongodb
  frontend:
    hostname: frontend
    build:
      context: ./web
      dockerfile: dockerfile
    ports:
      - "9000:3000"
    depends_on:
      - server

networks:
  mongo_net:
    driver: bridge
