version: '3.9'
volumes:
  data:
services:
  mongodb:
    image: mongo:latest
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    networks:
      - mongo_net
  server:
    hostname: backend
    build: 
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
    - ./backend:/app
    networks:
      - mongo_net

networks:
  mongo_net:
    driver: bridge