FROM node:18.11-alpine3.15
WORKDIR /app
RUN  npm install pm2 -g
COPY ./package.json .
RUN npm i
EXPOSE 5000 
ENV PORT=5000
ENV NODE_ENV=production
COPY . .
ENV DOCKER_DB_URI="mongodb://mongo-annotation:27017"
CMD [ "pm2-runtime", "npm", "--", "start" ]