version: '3.9'
volumes:
  data:
services:
  mongodb:
    image: mongo:latest
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    networks:
      - mongo_net
  server:
    hostname: backend
    build: 
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    networks:
      - mongo_net
    depends_on:
      - mongodb

networks:
  mongo_net:
    driver: bridge
