name: learnify
description: Online Learning Platform

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5

  # State Management
  provider: ^6.0.4

  # Network
  dio: ^4.0.6

  # UI
  google_fonts: ^3.0.1
  curved_navigation_bar: ^1.0.3
  fl_chart: ^0.55.2
  carousel_slider: ^4.1.1
  cached_network_image: ^3.2.2
  flutter_native_splash: ^2.2.14
  page_transition: ^2.0.9
  flutter_map: ^3.0.0
  flutter_switch: ^0.3.2
  geolocator: ^9.0.2

  # Model
  equatable: ^2.0.5
  collection: ^1.16.0
  tuple: ^2.0.1
  latlong2: ^0.8.1

  # Local Storage
  shared_preferences: ^2.0.15

  # Helpers
  image_picker: ^0.8.6
  intl: ^0.17.0

  async: ^2.9.0
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

  http_mock_adapter: ^0.3.3


flutter:

  uses-material-design: true

  assets:
    - assets/lang/
    - assets/images/
    - assets/flags/


flutter_native_splash:
  color: "#5F9DF7"
  image: assets/images/logo-dblue.png
  color_dark: "#1746A2"
  image_dark: assets/images/logo-lblue.png
  # android_12:
  #   image: assets/android12splash.png
  #   color: "#5F9DF7"
  #   icon_background_color: "#eeeeee"
  fullscreen: false