FROM python:3.9
WORKDIR /app
COPY ./requirements.txt ./requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt
COPY . /app
EXPOSE 8000
ENV DB_URI="mongodb://mongo:27017"
CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0"]