# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Mobile CI

on:
  push:
    branches: [ "master", "dev" ]
    paths:
      - 'learnify/mobile/**'
  pull_request:
    branches: [ "master", "dev" ]
    paths:
      - 'learnify/mobile/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - name: Clean the previous built
        working-directory: ./learnify/mobile
        run: flutter clean
      - name: Get the Flutter dependencies
        working-directory: ./learnify/mobile
        run: flutter pub get
      - name: Run the tests
        working-directory: ./learnify/mobile
        run: flutter test
      - name: Build the APK
        working-directory: ./learnify/mobile
        run: flutter build apk --split-per-abi
